---
version: "2.0"

services:
  cron:
    image: mobsikx/akash-mysql-restore:0.0.18
    env:
      - CMS_HOST=cms
      - CMS_DNS_A=hkfdsh.fans
      - MYSQL_DATABASE=exampledb
      - MYSQL_USER=user
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=password
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - BACKUP_PATH=<<PATH>>
      - BACKUP_KEY=<<KEY>>
      - BACKUP_SECRET=<<SECRET>>
      - BACKUP_PASSPHRASE=passphrase
    depends_on:
      - service: db
  db:
    image: mysql:latest
    env:
      - MYSQL_DATABASE=exampledb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    expose:
      - port: 3306
        to:
          - global: true
          - service: cron

profiles:
  compute:
    cron:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 1Gi
        storage:
          size: 1Gi
    db:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 1Gi
        storage:
          size: 1Gi
  placement:
    dcloud:
      pricing:
        cron:
          denom: uakt
          amount: 10000
        db:
          denom: uakt
          amount: 10000

deployment:
  cron:
    dcloud:
      profile: cron
      count: 1
  db:
    dcloud:
      profile: db
      count: 1
